$(document).ready(function() {
const frases = [
    "El café no es solo una bebida, es combustible para tus sueños.",
    "Como el café, tú también puedes despertar lo mejor en otros.",
    "Cada taza de café es una nueva oportunidad para brillar.",
    "Si el café puede transformar granos en energía, tú puedes transformar obstáculos en logros.",
    "El éxito viene gota a gota, como el café perfecto.",
    "Despierta, huele el café y conquista el día.",
    "Tu potencial es como el aroma del café: imposible de ignorar.",
    "El café te da energía, pero tú decides cómo usarla.",
    "Como el café recién molido, tus mejores ideas están por salir.",
    "El café es temporal, pero tus logros son permanentes.",
    "Incluso el café más fuerte necesita tiempo para prepararse.",
    "Como los granos de café, a veces necesitas presión para mostrar tu mejor versión.",
    "El café no se rinde hasta estar perfecto, tampoco tú deberías.",
    "Cada grano de café fue una vez solo una semilla con potencial.",
    "El café enseña paciencia: las mejores cosas toman su tiempo.",
    "Como el café expreso, concentrate en lo esencial.",
    "El café frío nunca despertó a nadie; mantén tu pasión caliente.",
    "Tuesta tus problemas como granos de café y conviértelos en energía.",
    "El café más amargo puede endulzarse; tus días difíciles también.",
    "Como el café, algunos días serás suave, otros días, intenso.",
    "Buenos días empiezan con buen café y mejor actitud.",
    "El café de la mañana es tu primer acto de amor propio del día.",
    "Despierta con propósito, no solo con cafeína.",
    "El café matutino es el ritual que prepara tu éxito diario.",
    "Como el amanecer, el café marca un nuevo comienzo.",
    "Tu mañana empieza con café, tu éxito empieza contigo.",
    "El café es el puente entre los sueños de la noche y los logros del día.",
    "Cada sorbo de café es un paso más cerca de tus metas.",
    "El café perfecto necesita tiempo; tú también para alcanzar la excelencia.",
    "Despierta, toma café, cambia el mundo.",
    "El café alimenta la productividad, pero tú diriges el resultado.",
    "Donde hay café, hay esperanza y buenas ideas.",
    "El café es el lubricante de la creatividad.",
    "Una reunión sin café es solo gente triste sentada junta.",
    "El café convierte \"no puedo\" en \"dame cinco minutos más\".",
    "Trabajar sin café es como manejar sin gasolina.",
    "El café no hace el trabajo por ti, pero hace que lo disfrutes más.",
    "La oficina funciona con café y sueños.",
    "El café es el socio silencioso de todos los grandes proyectos.",
    "Procafeinación: el arte de no hacer nada hasta tomar café.",
    "El café sabe mejor cuando se comparte con amigos.",
    "Una conversación sin café es solo una charla incompleta.",
    "Los mejores planes nacen en cafeterías.",
    "El café une a las personas como nada más puede hacerlo.",
    "Un amigo con café es un tesoro invaluable.",
    "Las cafeterías son oficinas de construcción de relaciones.",
    "El café: el idioma universal de la hospitalidad.",
    "Compartir café es compartir tiempo, y el tiempo es amor.",
    "Las mejores historias se cuentan con café en la mesa.",
    "El café crea comunidades, una taza a la vez.",
    "El café enseña que las mejores cosas vienen de procesos lentos.",
    "Como el café, la vida tiene diferentes intensidades y sabores.",
    "El café negro te enseña a apreciar la simplicidad.",
    "Cada taza de café es una meditación líquida.",
    "El café te recuerda que incluso lo amargo puede ser placentero.",
    "Como el café, tu valor se intensifica con el tiempo.",
    "El café enseña paciencia: no se puede apurar la perfección.",
    "La vida es como el café: depende de cómo la prepares.",
    "El café frío es café desperdiciado; no desperdicies tus oportunidades.",
    "Como el café, mantén tu esencia sin importar lo que te agreguen.",
    "Sé como el café: fuerte, aromático e imposible de ignorar.",
    "El café transforma agua simple en energía; transforma tu día simple en extraordinario.",
    "Si el café puede despertar tu cuerpo, tú puedes despertar tu potencial.",
    "Como el café, algunas personas te dan energía solo con su presencia.",
    "Filtra los comentarios negativos como filtras el café.",
    "Sé el café en el té de la vida: destaca por tu intensidad.",
    "Como el café descafeinado, sin pasión no eres tú mismo.",
    "El café no pretende ser otra cosa; tú tampoco deberías.",
    "La presión hace mejores granos de café y mejores versiones de ti.",
    "Como el café gourmet, invierte en tu calidad, no en tu cantidad.",
    "Tus sueños necesitan combustible; que sea café y determinación.",
    "Como el café importado, tus metas pueden venir de lejos pero valen la pena.",
    "El café une culturas; tus sueños pueden unir realidades.",
    "Persigue tus metas como persigues la cafetera por las mañanas.",
    "El café premium cuesta más pero vale la pena; invierte en tus sueños.",
    "Como el café de especialidad, tus metas requieren cuidado especial.",
    "El café viaja miles de kilómetros para llegar a ti; no te rindas en el camino.",
    "Tus objetivos son como el café perfecto: requieren tiempo, paciencia y pasión.",
    "Como el café orgánico, deja que tus sueños crezcan naturalmente.",
    "El café une el pasado (tradición) con el presente; conecta tus sueños con tu realidad.",
    "La vida es como un espresso: corta pero intensa.",
    "No necesitas una excusa para tomar café, pero el lunes es una buena razón.",
    "El café es prueba de que Dios nos ama y quiere que seamos felices.",
    "Algunos días necesitas café extra fuerte, otros días necesitas café extra largo.",
    "El café es mi grupo de apoyo líquido.",
    "Como el café irlandés, añade un poco de diversión a tu rutina.",
    "El café late es arte líquido; tu vida también puede ser una obra maestra.",
    "Incluso el café instantáneo es mejor que no tener café; incluso un pequeño paso es progreso.",
    "El café cold brew toma tiempo pero vale la pena; tus metas también.",
    "Al final del día, no importa cómo tomes tu café, lo importante es que nunca dejes de soñar."
];

  $('button').click(function() {
    const frase = frases[Math.floor(Math.random() * frases.length)];
    $('#quote')
      .stop(true, true)            // Detiene animaciones previas
      .text(frase)                 // Rellena con la nueva frase
      .fadeIn(400)                 // Aparece en 0.4s
      .delay(6000)                 // Se mantiene 6s
      .fadeOut(400);               // Desaparece en 0.4s
  });
});
